services:
  - type: web
    name: calorie-tracker-bot-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FOOD_API_KEY
        sync: false
    autoDeploy: true 